config/routes.rb
Octothorpe::Application.routes.draw do
  resources :contacts, :only => [:new, :create]
  
  namespace :admin do
    resources :pages
    resources :users
    resources :contacts
  end
  match '/admin/logout' => 'admin#logout', :as => :admin_logout
  match '/admin/login' => 'admin#login', :as => :admin_login
  match '/admin' => 'admin#index', :as => :admin
  match '/:title' => 'pages#show', :as => :page
  root :to => 'pages#show'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/page.rb
class Page < ActiveRecord::Base
  include ::Rails.application.routes.url_helpers
  def pretty_path
    page_path(:title => self.title_for_url)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  require 'bcrypt'
  attr_reader   :password

  validates_confirmation_of :password
  validates_presence_of     :password_digest
  
  def self.attributes_protected_by_default
    super + ['password_digest']
  end
  
  def authenticate(unencrypted_password)
    if BCrypt::Password.new(password_digest) == unencrypted_password
      self
    else
      false
    end
  end

  # Encrypts the password into the password_digest attribute.
  def password=(unencrypted_password)
    @password = unencrypted_password
    unless unencrypted_password.blank?
      self.password_digest = BCrypt::Password.create(unencrypted_password)
    end
  end
end

app/controllers/admin/contacts_controller.rb
class Admin::ContactsController < ApplicationController
  before_filter :login_required
  layout 'admin'
  
  def index
    @contacts = Contact.all
  end
  
  def show
    @contact = Contact.find(params[:id])
  end
  
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
  end
end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < ApplicationController
  before_filter :login_required
  layout 'admin'
  
  def index
    @pages = Page.all
  end
  
  def new
    @page = Page.new
  end
  
  def create
    @page = Page.new(params[:page])
    if @page.save
      redirect_to(admin_pages_url)
    else
      render 'new'
    end
  end
  
  def edit
    @page = Page.find(params[:id])
  end
  
  def update
    @page = Page.find(params[:id])
    if @page.update_attributes(params[:page])
      redirect_to(admin_pages_url)
    else
      render 'edit'
    end
  end
  
  def destroy
    @page = Page.find(params[:id])
    @page.destroy
    redirect_to(admin_pages_url)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :login_required
  layout 'admin'
  
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to(admin_users_url)
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to(admin_users_url)
    else
      render 'new'
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to(admin_users_url)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'
  
  def index
    render :login unless current_user
  end
  
  def login
    if params[:user]
      user = User.where(:name => params[:user][:name]).first
      if user and user.authenticate(params[:user][:password])
        session[:user_id] = user.id
      end
      redirect_to admin_url
    end
  end
  
  def logout
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def login_required
    redirect_to(admin_login_path) unless current_user
  end
  
  def page_not_found
    render :file => "#{Rails.root}/public/404.html", :status => :not_found, :layout => false
  end
  
  def current_user
    User.find(session[:user_id]) rescue nil
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end
  
  def create
    @contact = Contact.new(params[:contact])
    if @contact.save
      redirect_to(root_path, :notice => 'Thanks for your message!')
    else
      render 'new', :notice => "Something went wrong."
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    @page = Page.where(:title_for_url => (params[:title] || 'home')).first
    page_not_found if @page.nil?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    session[:user_id] ? true : false
  end
  
  def google_analytics(account_number)
    %Q[
      <script type="text/javascript" charset="utf-8">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', '#{account_number}']);
        _gaq.push(['_trackPageview']);
        (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
      </script>
    ]
  end
end

app/helpers/pages_helper.rb
module PagesHelper
  def link_to_page(page)
    link_to page.title, page.pretty_path
  end
end

app/views/admin/_admin_bar.html.erb
<%
  parts = []
  parts << "Administration"
  if params[:controller].split('/').include?("admin")
    parts << link_to("View Public Site", root_path)
  else
    parts << link_to("Back To Admin", admin_path)
  end
  parts << link_to("Logout", admin_logout_path) if logged_in?
%>
<div id="admin-bar">
  <%=raw parts.join(" | ") %>
</div>

app/views/admin/_top_menu.html.erb
<ul id="top-nav">
  <li><%= link_to "Admin Home", admin_path %></li>
  <li><%= link_to "Pages", admin_pages_path %></li>
  <li><%= link_to "Users", admin_users_path %></li>
  <li><%= link_to "Contacts", admin_contacts_path %></li>
</ul>

app/views/admin/contacts/index.html.erb
<h1>Contact</h1>

<table id="contacts">
  <thead>
    <tr>
      <th>
        Name
      </th>
      <th>
        Email
      </th>
      <th>
        Subject
      </th>
    </tr>
  </thead>
  <tbody>
    <% @contacts.each do |contact| %>
      <%= content_tag_for :tr, contact do %>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.subject %></td>
        <td><%= link_to "View", admin_contact_path(contact) %></td>
        <td><%= link_to "Delete", admin_contact_path(contact), :method => :delete, :confirm => 'Are you sure?' %></td>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/admin/contacts/show.html.erb
<p>
  <strong>Name:</strong><br />
  <%= @contact.name %>
</p>
<p>
  <strong>Email:</strong><br />
  <%= @contact.email %>
</p>
<p>
  <strong>Subject:</strong><br />
  <%= @contact.subject %>
</p>
<p>
  <strong>Message:</strong><br />
  <%=raw h(@contact.content).gsub(/\n/,'<br />') %>
</p>
<p>
  <%= link_to "Delete", admin_contact_path(@contact), :method => :delete, :confirm => 'Are you sure?' %>
</p>

app/views/admin/index.html.erb
WELCOME

app/views/admin/login.html.erb
<%= semantic_form_for(User.new, :url => admin_login_path) do |form| %>
  <%= form.inputs do %>
    <%= form.input :name, :label => 'Username', :required => false %>
    <%= form.input :password %>
  <% end %>
  <%= form.buttons do %>
    <%= form.commit_button :button_html => {:value => 'Login'} %>
  <% end %>
<% end %>

app/views/admin/pages/_form.html.erb
<%= semantic_form_for([:admin, @page]) do |form| %>
  <%= form.inputs do %>
    <%= form.input :title %>
    <%= form.input :title_for_url, :label => "Title for URL", :as => :string, :input_html => {'data-changed' => !form.object.title_for_url.blank?} %>
    <%= form.input :content %>
    <%= form.input :style, :required => false %>
  <% end %>
  
  <%= form.buttons :commit %>
<% end %>
<% content_for :page_javascripts do %>
  <script type="text/javascript" charset="utf-8">
    (function($) {
      $(document).ready(function() {
        $('#page_title').keyup(function() {
          if (!$('#page_title_for_url').attr('data-changed')) {
            $('#page_title_for_url').val($(this).val().replace(/[^a-zA-Z0-9\-\_]/g, '-'))
          }
        })
        $('#page_title_for_url').keyup(function() {
          $(this).attr("data-changed", true)
        })
      })
    })(jQuery)
  </script>
<% end %>

app/views/admin/pages/edit.html.erb
<%= render 'form' %>

app/views/admin/pages/index.html.erb
<h1>Pages</h1>

<%= link_to "New Page", new_admin_page_path %>
<table id="pages">
  <thead>
    <tr>
      <th>
        Title
      </th>
      <th>
        URL
      </th>
    </tr>
  </thead>
  <tbody>
    <% @pages.each do |page| %>
      <%= content_tag_for :tr, page do %>
        <td><%= page.title %></td>
        <td><%= page.pretty_path %></td>
        <td><%= link_to "View", page.pretty_path %></td>
        <td><%= link_to "Edit", edit_admin_page_path(page) %></td>
        <td><%= link_to "Delete", admin_page_path(page), :method => :delete, :confirm => 'Are you sure?' %></td>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/admin/pages/new.html.erb
<%= render 'form' %>

app/views/admin/users/_form.html.erb
<%= semantic_form_for([:admin, @user]) do |form| %>
  <%= form.inputs do %>
    <%= form.input :name, :label => 'Username' %>
    <%= form.input :password, :required => form.object.new_record? %>
    <%= form.input :password_confirmation, :label => 'Password Confirmation', :required => form.object.new_record? %>
  <% end %>
  <%= form.buttons do %>
    <%= form.commit_button %>
  <% end %>
<% end %>

app/views/admin/users/edit.html.erb
<%= render 'form' %>

app/views/admin/users/index.html.erb
<h1>Users</h1>

<%= link_to "New User", new_admin_user_path %>
<table id="users">
  <thead>
    <tr>
      <th>
        Name
      </th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <%= content_tag_for :tr, user do %>
        <td><%= user.name %></td>
        <td><%= link_to "Edit", edit_admin_user_path(user) %></td>
        <td><%= link_to "Delete", admin_user_path(user), :method => :delete, :confirm => 'Are you sure?' %></td>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/admin/users/new.html.erb
<%= render 'form' %>

app/views/contacts/new.html.erb
<%= semantic_form_for(@contact) do |form| %>
  <%= form.inputs do %>
    <%= form.input :name %>
    <%= form.input :email %>
    <%= form.input :subject %>
    <%= form.input :content, :label => 'Message', :input_html => {:rows => 5} %>
  <% end %>
  
  <%= form.buttons do %>
    <%= form.commit_button :button_html => {:value => 'Send'} %>
  <% end %>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Octothorpe</title>
  <%= stylesheet_link_tag 'application' %>
  <%= stylesheet_link_tag 'admin' %>
  <%= stylesheet_link_tag 'formtastic' %>
  <%= stylesheet_link_tag 'formtastic_changes' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <%= yield :page_javascripts %>
</head>
<body>
  <%= render 'admin/admin_bar' if logged_in? %>
  <div id="header-container">
    <div id="header">
      <div id="company-name">
        Octothor.pe
      </div>
      <div id="top-nav-container">
        <%= render 'admin/top_menu' %>
      </div>
    </div>
  </div>
  <div id="notice">
    <%= notice %>
  </div>
  <div id="page-content">
    <%= yield %>
  </div>
  <div id="footer">
    <%= render 'shared/copyright' %>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Octothorpe</title>
  <%= stylesheet_link_tag 'application' %>
  <%= stylesheet_link_tag @page.title_for_url if @page %>
  <%= stylesheet_link_tag 'formtastic' %>
  <%= stylesheet_link_tag 'formtastic_changes' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <%= yield :page_javascripts %>
  <style type="text/css" media="screen">
    <%= yield :page_style %>
  </style>
  <%=raw google_analytics(GOOGLE_ACCOUNT_NUMBER) %>
</head>
<body>
  <%= render 'admin/admin_bar' if logged_in? %>
  <div id="header-container">
    <div id="header">
      <div id="company-name">
        Octothor.pe
      </div>
      <div id="top-nav-container">
        <%= render 'shared/top_menu' %>
      </div>
    </div>
  </div>
  <div id="notice">
    <%= notice %>
  </div>
  <div id="page-content">
    <%= yield %>
  </div>
  <div id="footer">
    <%= render 'shared/copyright' %>
  </div>
</body>
</html>

app/views/pages/show.html.erb
<%=raw @page.content %>
<%= content_for :page_style do %>
  <% @page.style %>
<% end %>

app/views/shared/_copyright.html.erb
Copyright &copy; <%= Time.now.year %> Octothor.pe

app/views/shared/_top_menu.html.erb
<ul id="top-nav">
  <% Page.all.each do |page| %>
    <li><%= link_to_page(page) %></li>
  <% end %>
  <li><%= link_to "Contact", new_contact_path %>
</ul>